// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASmm4ttcUVVGJdQoEJQHmMxAAqYTe3BIs',
    appId: '1:973335419103:android:6514416d6d698074acb16a',
    messagingSenderId: '973335419103',
    projectId: 'bookapp-73219',
    databaseURL: 'https://bookapp-73219-default-rtdb.firebaseio.com',
    storageBucket: 'bookapp-73219.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG0Ys6EUEcnZwoTMNGuXbMzUZojJOVFNg',
    appId: '1:973335419103:ios:267a32d9b6d5a23facb16a',
    messagingSenderId: '973335419103',
    projectId: 'bookapp-73219',
    databaseURL: 'https://bookapp-73219-default-rtdb.firebaseio.com',
    storageBucket: 'bookapp-73219.appspot.com',
    androidClientId: '973335419103-om9h1ka65f0dpqvork25oianpuo2gl7e.apps.googleusercontent.com',
    iosClientId: '973335419103-6jpr32824h5a45ad4ebol02j8l2675f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp8bftqLCY6A0HWRyUC5WrVTSjnGRzvH8',
    appId: '1:973335419103:web:352afea225589d98acb16a',
    messagingSenderId: '973335419103',
    projectId: 'bookapp-73219',
    authDomain: 'bookapp-73219.firebaseapp.com',
    databaseURL: 'https://bookapp-73219-default-rtdb.firebaseio.com',
    storageBucket: 'bookapp-73219.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG0Ys6EUEcnZwoTMNGuXbMzUZojJOVFNg',
    appId: '1:973335419103:ios:267a32d9b6d5a23facb16a',
    messagingSenderId: '973335419103',
    projectId: 'bookapp-73219',
    databaseURL: 'https://bookapp-73219-default-rtdb.firebaseio.com',
    storageBucket: 'bookapp-73219.appspot.com',
    androidClientId: '973335419103-om9h1ka65f0dpqvork25oianpuo2gl7e.apps.googleusercontent.com',
    iosClientId: '973335419103-6jpr32824h5a45ad4ebol02j8l2675f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensesTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp8bftqLCY6A0HWRyUC5WrVTSjnGRzvH8',
    appId: '1:973335419103:web:352afea225589d98acb16a',
    messagingSenderId: '973335419103',
    projectId: 'bookapp-73219',
    authDomain: 'bookapp-73219.firebaseapp.com',
    databaseURL: 'https://bookapp-73219-default-rtdb.firebaseio.com',
    storageBucket: 'bookapp-73219.appspot.com',
  );

}